default_email: "ndt8895@gmail.com"
role_admin: 0
role_user: 1
per_page: 5
number_questions_per_examination: 20
default_spent_time: 0
admin:
  users:
    size: "70x70"
    url_ava: "assets/avata.jpg"
users:
  size: "50x50"
  size_ava: "100x100"
  url_ava: "/assets/user_3.png"
  pic_size: 5
question_type:
  single_choise: 1
  multiple_choise: 2
  text: 3
MINUTE: 60
TIME_FORMAT: "%H:%M:%S"
DATETIME: "%d/%m/%Y"
default_time: "00:00:00"
